os: osx
language: swift

jobs:
  include:
    - osx_image: xcode11.3  # macOS 10.14.6
    - osx_image: xcode12.2  # macOS 10.15.7
    - osx_image: xcode12.3  # macOS 11.1
    - osx_image: xcode12.4  # macOS 11.2.1
    - osx_image: xcode12.5  # macOS 11.3

script: swift test --enable-test-discovery
