name: CI
on:
  pull_request:
    paths:
      - '**/*.swift'
      - .github/workflows/ci.yml
  schedule:
    - cron: '3 3 * * 0'  # 3:03 AM, every Sunday
jobs:
  macOS:
    runs-on: macos-latest
    strategy:
      matrix:
        swift:
          - 5.1
          - 5.2
          - 5.3
        premature:
          - false
        include:
          - swift: 5.4
            premature: true
    steps:
    - uses: actions/checkout@v2
    - uses: mxcl/xcodebuild@v1
      with:
        swift: ${{ matrix.swift }}
      continue-on-error: ${{ matrix.premature }}
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
    container:
      image: swift:${{ matrix.swift }}
    steps:
    - uses: actions/checkout@v2
    - run: swift test -Xswiftc -suppress-warnings --enable-test-discovery
